@extends('layouts.layout')
@section('meta_title', 'Privacy Policy | YogIntra')
@section('meta_description', 'How YogIntra collects, uses and protects personal information.')
@section('content')
<section class="inner-header divider layer-overlay overlay-dark-5" data-bg-img="{{ asset('assets/bg/bg6.jpg') }}"><div class="container pt-70 pb-20"><div class="text-center"><h1 class="title text-white">Privacy Policy</h1><ol class="breadcrumb text-center mt-10"><li class="text-white"><a class="text-white" href="{{ url('/') }}">Home</a></li><li class="active text-gray">Privacy Policy</li></ol></div></div></section>
<section class="privacy-policy-page"><div class="container pt-50 pb-70"><article class="privacy-policy-card">
<header><h2>Privacy Policy</h2><p><strong>Last Updated: September 14, 2026</strong></p></header>
<p>At YogIntra, we respect your privacy and are committed to protecting the personal information you share with us. This Privacy Policy explains how YogIntra collects, uses, stores, protects, and may disclose information when you visit our website, contact us, book a yoga service, participate in our programs, or otherwise interact with us.</p>
<p>By using the YogIntra website or services, you acknowledge that you have read and understood this Privacy Policy. If you do not agree with this policy, please discontinue use of the website and services.</p>
<h3>1. About YogIntra</h3><p>YogIntra provides yoga and wellness services, including Home Visit Yoga, Private Online Yoga, Group Online Yoga, Corporate Yoga, Yoga Center sessions, Yoga Teacher Training Courses (TTC), Retreats, Workshops, and related wellness programs.</p><p>Our website may allow visitors to learn about our services, submit enquiries, request appointments, contact our team, and access information about yoga and wellness.</p>
<h3>2. Information We Collect</h3><p>Depending on how you interact with YogIntra, we may collect different types of information.</p><h4>Personal Information</h4><p>We may collect information such as:</p><ul><li>Full name</li><li>Phone number</li><li>Email address</li><li>Country, state, city, or location</li><li>Service preferences</li><li>Appointment or booking information</li><li>Messages, enquiries, and other information you voluntarily submit</li><li>Payment and transaction information when you purchase a service</li><li>Information required to provide or manage a requested service</li></ul><p>You should provide information that is accurate and up to date.</p><h4>Technical Information</h4><p>When you visit our website, certain technical information may be collected automatically, depending on the website's technology and services in use.</p><p>This may include:</p><ul><li>IP address</li><li>Browser type</li><li>Device type</li><li>Operating system</li><li>Website pages visited</li><li>Date and time of visits</li><li>Referring website</li><li>General usage and interaction information</li></ul><p>This information may help us understand website usage, maintain security, improve website performance, and enhance user experience.</p>
<h3>3. Information You Provide Through Forms</h3><p>YogIntra may provide enquiry and appointment forms through its website.</p><p>For example, a user may be asked to provide their name, phone number, email address, location, preferred service, and message or enquiry details.</p><p>We use this information to respond to your enquiry, understand your requirements, arrange appointments, and provide requested services.</p>
<h3>4. How We Use Your Information</h3><p>YogIntra may use personal information for legitimate business and service-related purposes, including:</p><ul><li>Responding to enquiries and requests.</li><li>Scheduling and managing yoga sessions.</li><li>Processing bookings and payments.</li><li>Providing yoga and wellness services.</li><li>Communicating with customers regarding appointments or services.</li><li>Confirming or modifying bookings.</li><li>Providing customer support.</li><li>Processing refunds, cancellations, or rescheduling requests.</li><li>Improving our website, services, and customer experience.</li><li>Sending service-related communications.</li><li>Sending promotional or marketing communications where permitted by applicable law.</li><li>Preventing fraud, misuse, and unauthorized activity.</li><li>Maintaining website security.</li><li>Complying with applicable legal and regulatory requirements.</li></ul>
<h3>5. Payment Information</h3><p>If you make a payment for a YogIntra service, payment information may be processed through a third-party payment gateway or financial service provider.</p><p>Where applicable, payment providers may collect and process information necessary to complete the transaction.</p><p>YogIntra generally does not need to store complete payment-card information on its own systems when such information is processed directly by an authorized third-party payment provider.</p><p>Third-party payment providers may have their own privacy policies and terms. We recommend reviewing those policies before completing a transaction.</p>
<h3>6. Cookies and Similar Technologies</h3><p>The YogIntra website may use cookies and similar technologies to improve website functionality, understand visitor activity, remember preferences, and analyze website performance.</p><p>Cookies may be used for purposes such as:</p><ul><li>Website functionality.</li><li>User preferences.</li><li>Analytics.</li><li>Security.</li><li>Performance monitoring.</li><li>Marketing or advertising, where applicable.</li></ul><p>You may be able to control or disable cookies through your browser settings. However, disabling certain cookies may affect some website functionality.</p>
<h3>7. Analytics and Website Performance</h3><p>YogIntra may use analytics or similar technologies to understand how visitors use the website.</p><p>Analytics information may help us understand which pages are visited, how users navigate the website, and how the website performs.</p><p>Where third-party analytics services are used, those providers may process information according to their own privacy policies and applicable terms.</p>
<h3>8. Marketing Communications</h3><p>Where legally permitted and where appropriate consent has been obtained, YogIntra may use your contact information to communicate information about yoga classes, workshops, retreats, teacher training, offers, events, or other services.</p><p>You may request to stop receiving promotional communications at any time by contacting us or using an available unsubscribe mechanism.</p><p>Service-related communications, such as booking confirmations, appointment information, payment notifications, or important account/service updates, may continue where necessary.</p>
<h3>9. How We Share Information</h3><p>YogIntra does not intend to sell your personal information.</p><p>We may share information where reasonably necessary to operate our business and provide requested services, including with:</p><ul><li>Yoga instructors or service providers involved in delivering your requested service.</li><li>Payment processors and financial institutions.</li><li>Website hosting, technology, analytics, or IT service providers.</li><li>Communication or customer-support service providers.</li><li>Professional advisers where reasonably necessary.</li><li>Government authorities or law-enforcement agencies where required by applicable law.</li><li>Other parties where disclosure is necessary to protect YogIntra's rights, users, property, or security.</li></ul><p>Third-party service providers may only receive information reasonably necessary for the services they provide, subject to applicable contractual, legal, and privacy requirements.</p>
<h3>10. Third-Party Websites</h3><p>The YogIntra website may contain links to third-party websites, social media platforms, payment services, or other external resources.</p><p>YogIntra does not control the privacy practices, content, security, or policies of third-party websites.</p><p>When you leave the YogIntra website, your information may be subject to the privacy policy of the third-party website you visit.</p><p>We recommend reviewing the privacy policies of external websites before submitting personal information.</p>
<h3>11. Data Security</h3><p>YogIntra takes reasonable measures to protect personal information against unauthorized access, misuse, loss, alteration, or disclosure.</p><p>However, no website, online service, electronic transmission, or storage system can be guaranteed to be completely secure.</p><p>You acknowledge that providing information through the internet involves certain risks, and YogIntra cannot guarantee absolute security of information transmitted online.</p>
<h3>12. Data Retention</h3><p>We retain personal information only for as long as reasonably necessary for the purposes described in this Privacy Policy, including providing services, maintaining business records, resolving disputes, enforcing agreements, complying with legal obligations, and protecting our legitimate interests.</p><p>The length of time information is retained may depend on the type of information and the purpose for which it was collected.</p><p>When information is no longer reasonably required, it may be securely deleted, anonymized, or otherwise disposed of where appropriate.</p>
<h3>13. Your Privacy Rights</h3><p>Depending on applicable law, you may have certain rights regarding your personal information.</p><p>These rights may include the ability to:</p><ul><li>Request access to personal information we hold about you.</li><li>Request correction of inaccurate or incomplete information.</li><li>Request deletion of personal information where legally applicable.</li><li>Withdraw consent where processing is based on consent.</li><li>Request information about how your personal information is used.</li><li>Object to certain types of processing where applicable.</li><li>Request restriction of processing in circumstances permitted by law.</li><li>Opt out of certain promotional communications.</li></ul><p>Requests may be subject to applicable legal requirements and reasonable identity verification.</p>
<h3>14. Children's Privacy</h3><p>YogIntra may offer yoga programs suitable for different age groups. However, our website is not intended to knowingly collect personal information from children without appropriate parental or guardian involvement where required by applicable law.</p><p>If a parent or legal guardian believes that a child has provided personal information without appropriate authorization, please contact us so that we can review and take appropriate action.</p>
<h3>15. Health and Wellness Information</h3><p>Some YogIntra services may involve information voluntarily provided by a participant regarding physical limitations, injuries, health conditions, or other circumstances relevant to participation.</p><p>Users should only provide health-related information when necessary for their participation or service requirements.</p><p>Where such information is collected, YogIntra will handle it with appropriate care and in accordance with applicable legal requirements.</p><p>Yoga and wellness services are not a substitute for professional medical diagnosis or treatment.</p>
<h3>16. Information Provided by You About Other People</h3><p>If you provide YogIntra with personal information belonging to another person, such as a family member, employee, student, or participant, you should ensure that you have the appropriate authority or permission to provide that information.</p><p>You are responsible for ensuring that such information is provided lawfully.</p>
<h3>17. Business Transfers</h3><p>If YogIntra undergoes a merger, restructuring, acquisition, sale of assets, or other business transaction, personal information may be transferred as part of that transaction where legally permitted.</p><p>Any such transfer will be handled in accordance with applicable privacy laws.</p>
<h3>18. International Data Transfers</h3><p>Depending on the technology providers, instructors, payment processors, hosting services, or other service providers used by YogIntra, personal information may be processed or stored in locations outside your state or country.</p><p>Where required by applicable law, appropriate safeguards will be used for such transfers.</p>
<h3>19. Changes to This Privacy Policy</h3><p>YogIntra may update this Privacy Policy from time to time to reflect changes in our services, website functionality, technology, business practices, or applicable laws.</p><p>When we make changes, we will update the "Last Updated" date at the beginning of this policy.</p><p>We encourage users to review this Privacy Policy periodically to stay informed about how their information is handled.</p>
<h3>20. Legal Compliance</h3><p>YogIntra will process personal information in accordance with applicable privacy and data-protection laws.</p><p>Where required by law, we may disclose information to government authorities, regulators, courts, law-enforcement agencies, or other authorized parties.</p>
<h3>21. Your Consent</h3><p>By using the YogIntra website, submitting an enquiry, requesting a service, making a booking, or providing personal information to us, you acknowledge that you have read this Privacy Policy.</p><p>Where applicable law requires specific consent for a particular type of processing, YogIntra will seek such consent through an appropriate mechanism.</p>
<h3>22. Contact Us</h3><p>If you have questions about this Privacy Policy, want to exercise an applicable privacy right, or have concerns about how your personal information is handled, please contact YogIntra.</p><address><strong>YogIntra</strong><br>D-408 Shivlila Apt, Mumbra Devi Colony Road,<br>Diva East, Thane – 400612, India<br>Phone: <a href="tel:+919867291573">+91-9867291573</a><br>Email: <a href="mailto:support@yogintra.com">support@yogintra.com</a></address>
<h3>23. Acceptance of This Privacy Policy</h3><p>By continuing to use the YogIntra website and services, you acknowledge that you have read and understood this Privacy Policy.</p><p>If you do not agree with the practices described in this policy, please discontinue use of the website and services.</p>
</article></div></section>
<style>.privacy-policy-page{background:#f7fafb}.privacy-policy-card{max-width:960px;margin:auto;padding:42px;border:1px solid #deebed;border-radius:14px;background:#fff;box-shadow:0 10px 30px rgba(15,63,73,.08);color:#45636b;font-size:16px;line-height:1.72}.privacy-policy-card header{margin-bottom:28px;padding-bottom:20px;border-bottom:1px solid #dce9eb;text-align:center}.privacy-policy-card h2{margin:0 0 8px;color:#123f4a;font-weight:800}.privacy-policy-card h3{margin:32px 0 10px;color:#123f4a;font-size:21px;font-weight:800}.privacy-policy-card h4{margin:18px 0 7px;color:#1b5661;font-size:16px;font-weight:800}.privacy-policy-card p{margin:0 0 14px}.privacy-policy-card ul{display:block!important;margin:0 0 16px!important;padding-left:30px!important;list-style:disc outside!important}.privacy-policy-card ul li{display:list-item!important;margin:6px 0!important;padding-left:4px!important;list-style-type:disc!important}.privacy-policy-card ul li::marker{color:#16717a!important;font-size:1.1em}.privacy-policy-card address{margin:0;font-style:normal}.privacy-policy-card a{color:#126bca;text-decoration:underline}@media(max-width:767px){.privacy-policy-card{padding:28px 22px;font-size:15px}.privacy-policy-card h3{font-size:19px}}</style>
@endsection
