@extends('layouts.layout')
@section('meta_title', 'Privacy Policy | YogIntra')
@section('meta_description', 'How YogIntra collects, uses and protects personal information.')
@section('content')
<section class="inner-header divider layer-overlay overlay-dark-5" data-bg-img="{{ asset('assets/bg/bg6.jpg') }}"><div class="container pt-70 pb-20"><div class="text-center"><h1 class="title text-white">Privacy Policy</h1><ol class="breadcrumb text-center mt-10"><li class="text-white"><a class="text-white" href="{{ url('/') }}">Home</a></li><li class="active text-gray">Privacy Policy</li></ol></div></div></section>
<section class="privacy-policy-page"><div class="container pt-50 pb-70"><article class="privacy-policy-card">
<header><h2>Privacy Policy</h2><p><strong>Last Updated: September 14, 2026</strong></p></header>
<p>At YogIntra, we respect your privacy and protect the personal information you share with us. This policy explains how we collect, use, store, protect, and may disclose information when you visit our website, contact us, book a yoga service, join our programs, or otherwise interact with us.</p>
<p>By using YogIntra’s website or services, you acknowledge that you have read and understood this Privacy Policy. If you do not agree, please discontinue use of the website and services.</p>
<h3>1. About YogIntra</h3><p>YogIntra provides Home Visit Yoga, Private and Group Online Yoga, Corporate Yoga, Yoga Center sessions, TTC, Retreats, Workshops, and related wellness programs.</p>
<h3>2. Information We Collect</h3><p>We may collect personal information and technical information, depending on how you interact with us.</p><h4>Personal information</h4><ul><li>Full name, phone number, and email address</li><li>Country, state, city, location, and service preferences</li><li>Appointment, booking, payment, transaction, message, and enquiry information</li><li>Information needed to provide or manage a requested service</li></ul><h4>Technical information</h4><ul><li>IP address, browser type, device type, and operating system</li><li>Pages visited, date and time of visits, and referring website</li><li>General website usage and interaction information</li></ul>
<h3>3. Information You Provide Through Forms</h3><p>We use form information to respond to enquiries, understand your requirements, arrange appointments, and provide requested services.</p>
<h3>4. How We Use Your Information</h3><ul><li>Respond to enquiries and provide, schedule, or manage yoga services</li><li>Process bookings, payments, refunds, cancellations, and rescheduling</li><li>Communicate about appointments, services, support, and permitted marketing</li><li>Improve our website and customer experience; prevent fraud; maintain security; and comply with legal obligations</li></ul>
<h3>5. Payment Information</h3><p>Payments may be processed through third-party payment gateways or financial service providers. YogIntra generally does not store complete payment-card information when it is processed directly by an authorised provider.</p>
<h3>6. Cookies and Similar Technologies</h3><p>We may use cookies for:</p><ul><li>Website functionality and user preferences</li><li>Analytics, security, and performance monitoring</li><li>Marketing or advertising where applicable</li></ul><p>You may control cookies through browser settings, although disabling some cookies may affect functionality.</p>
<h3>7. Analytics and Website Performance</h3><p>Analytics may help us understand website usage, navigation, and performance. Third-party providers process information under their own policies.</p>
<h3>8. Marketing Communications</h3><p>Where legally permitted and appropriately consented to, we may communicate about classes, workshops, retreats, teacher training, offers, events, and services. You may stop promotional communications at any time.</p>
<h3>9. How We Share Information</h3><p>YogIntra does not intend to sell your personal information. We may share information where reasonably necessary with:</p><ul><li>Instructors and service providers delivering your requested service</li><li>Payment processors, hosting, technology, analytics, IT, and customer-support providers</li><li>Professional advisers or authorised government and law-enforcement bodies where legally required</li><li>Parties needed to protect YogIntra’s rights, users, property, or security</li></ul>
<h3>10. Third-Party Websites</h3><p>External websites, social platforms, and payment services have independent privacy practices. Please review their policies before submitting personal information.</p>
<h3>11. Data Security</h3><p>We take reasonable measures to protect information against unauthorised access, misuse, loss, alteration, or disclosure. No online transmission or storage system can be completely secure.</p>
<h3>12. Data Retention</h3><p>We retain personal information only as reasonably necessary to provide services, maintain records, resolve disputes, enforce agreements, comply with legal obligations, and protect legitimate interests.</p>
<h3>13. Your Privacy Rights</h3><p>Depending on applicable law, you may be able to:</p><ul><li>Request access, correction, deletion, restriction, or information about use of your data</li><li>Withdraw consent or object to certain processing where applicable</li><li>Opt out of promotional communications</li></ul>
<h3>14. Children’s Privacy</h3><p>We do not knowingly collect children’s personal information without appropriate parental or guardian involvement where required by law.</p>
<h3>15. Health and Wellness Information</h3><p>Health-related information should be provided only when necessary for participation. Yoga and wellness services are not a substitute for professional medical diagnosis or treatment.</p>
<h3>16. Information About Other People</h3><p>If you provide another person’s information, you must have the appropriate authority or permission to do so lawfully.</p>
<h3>17. Business Transfers</h3><p>Information may be transferred as part of a merger, restructuring, acquisition, sale of assets, or other legally permitted transaction.</p>
<h3>18. International Data Transfers</h3><p>Information may be processed or stored outside your state or country. Appropriate safeguards will be used where required by law.</p>
<h3>19. Changes to This Privacy Policy</h3><p>We may update this policy as services, technology, business practices, or applicable laws change. We will update the Last Updated date when changes are made.</p>
<h3>20. Legal Compliance</h3><p>We process personal information in accordance with applicable privacy and data-protection laws and may disclose it to authorised parties where required by law.</p>
<h3>21. Your Consent</h3><p>By using our website, submitting an enquiry, requesting a service, making a booking, or providing personal information, you acknowledge this Privacy Policy.</p>
<h3>22. Contact Us</h3><address><strong>YogIntra</strong><br>D-408 Shivlila Apt, Mumbra Devi Colony Road,<br>Diva East, Thane – 400612, India<br>Phone: <a href="tel:+919867291573">+91-9867291573</a><br>Email: <a href="mailto:support@yogintra.com">support@yogintra.com</a></address>
<h3>23. Acceptance of This Privacy Policy</h3><p>By continuing to use YogIntra’s website and services, you acknowledge that you have read and understood this Privacy Policy. If you do not agree, please discontinue use of the website and services.</p>
</article></div></section>
<style>.privacy-policy-page{background:#f7fafb}.privacy-policy-card{max-width:960px;margin:auto;padding:42px;border:1px solid #deebed;border-radius:14px;background:#fff;box-shadow:0 10px 30px rgba(15,63,73,.08);color:#45636b;font-size:16px;line-height:1.72}.privacy-policy-card header{margin-bottom:28px;padding-bottom:20px;border-bottom:1px solid #dce9eb;text-align:center}.privacy-policy-card h2{margin:0 0 8px;color:#123f4a;font-weight:800}.privacy-policy-card h3{margin:32px 0 10px;color:#123f4a;font-size:21px;font-weight:800}.privacy-policy-card h4{margin:18px 0 7px;color:#1b5661;font-size:16px;font-weight:800}.privacy-policy-card p{margin:0 0 14px}.privacy-policy-card ul{display:block!important;margin:0 0 16px!important;padding-left:30px!important;list-style:disc outside!important}.privacy-policy-card ul li{display:list-item!important;margin:6px 0!important;padding-left:4px!important;list-style-type:disc!important}.privacy-policy-card ul li::marker{color:#16717a!important;font-size:1.1em}.privacy-policy-card address{margin:0;font-style:normal}.privacy-policy-card a{color:#126bca;text-decoration:underline}@media(max-width:767px){.privacy-policy-card{padding:28px 22px;font-size:15px}.privacy-policy-card h3{font-size:19px}}</style>
@endsection
